version: "3.9"
services:

  # --------------------------------------#
  #     Postgres data Warehouse           #
  # --------------------------------------#
  postgres:
    image: postgres:14.1-alpine
    command:
      - postgres
      - -c
      - max_connections=150
    environment:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_DB: $POSTGRES_DB
    healthcheck:
      interval: 10s
      retries: 60
      start_period: 2s
      test: pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER} | grep "accepting connections" || exit 1
      timeout: 2s
    ports:
    - published: 5433
      target: 5432
    restart: on-failure

  # --------------------------------------#
  #             DBT CLI               #
  # --------------------------------------#
  dbt-cli:
    image: ghcr.io/dbt-labs/dbt-postgres:1.3.latest
    entrypoint: "bash"
    working_dir: "/root/dbt/etl_spike"
    volumes:
      - "../dbt:/root/dbt"
      - ../great_expectations:/root/great_expectations
    environment:
      DBT_PROFILES_DIR: /root/dbt
    profiles: ["dbt-cli"]

  # --------------------------------------#
  #         Great Expectations Data Docs  #
  # --------------------------------------#
  great_expectations:
    build: ./great_expectations 
    working_dir: "/root"
    entrypoint: "bash"
    #command: "great_expectations docs build"
    volumes:
      - ../great_expectations:/root/great_expectations
    profiles: ["great_expectations"]

  # --------------------------------------#
  #   Prefect Orion Server                #
  # --------------------------------------#
  prefect-server:
    image: prefecthq/prefect:2.6.6-python3.11
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["prefect", "orion", "start"]
    environment:
      - PREFECT_ORION_API_HOST=0.0.0.0
      - PREFECT_ORION_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@prefect-database:5432/orion
    ports:
      - 4200:4200
    depends_on:
      - prefect-database
    profiles: ["prefect-server"]

  # --------------------------------------#
  #             Prefect Agent             #
  # --------------------------------------#
  agent:
    #image: prefecthq/prefect:2.6.6-python3.11
    build: ./prefect-cli 
    restart: always
    entrypoint: ["prefect", "agent", "start", "-q", "default"]
    working_dir: "/root/flows"
    volumes:
      - "../prefect/flows:/root/flows"
      - ../great_expectations:/root/great_expectations
      - ../dbt:/root/dbt
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
      DBT_PROFILES_DIR: /root/dbt
    #   Use PREFECT_API_KEY if connecting the agent to Prefect Cloud
    #  - PREFECT_API_KEY=YOUR_API_KEY
    depends_on:
      - prefect-server
    profiles: ["prefect-server"]

  # --------------------------------------#
  #             Prefect CLI               #
  # --------------------------------------#
  prefect-cli:
    build: ./prefect-cli 
    entrypoint: "bash"
    working_dir: "/root/flows"
    volumes:
      - "../prefect/flows:/root/flows"
      - ../great_expectations:/root/great_expectations
      - ../dbt:/root/dbt
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
      PREFECT_LOGGING_LEVEL: DEBUG
      DBT_PROFILES_DIR: /root/dbt
      #Use PREFECT_API_KEY to use the CLI to interact with Prefect Cloud
      #- PREFECT_API_KEY=YOUR_API_KEY
    profiles: ["prefect-cli"]

  # --------------------------------------#
  #       Prefect internal database       #
  # --------------------------------------#
  prefect-database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orion
    expose:
      - 5432
    # if you dont have volumes you cant really add blocks or deployments
    volumes: 
      - db:/var/lib/postgresql/data
    profiles: ["prefect-server"]

  # --------------------------------------#
  #   MinIO for Prefect flow storage      #
  # --------------------------------------#
  minio:
    image: minio/minio:latest
    entrypoint: ["minio", "server", "--address", "0.0.0.0:9000", "--console-address", "0.0.0.0:9001", "/data"]
    volumes:
      - "minio:/data"
    ports:
      - 9000:9000
      - 9001:9001
    profiles: ["prefect-server"]

volumes:
  prefect:
  db:
  minio:
networks:
  default:
    name: prefect-network
