version: 2

sources:
  - name: public
    description: Data from application database, brought in by an EL process. Seeded for tutorial purposes
    tables:
      - name: raw_customers
        columns:
        - name: id
          tests:
            - not_null
            - unique
        - name: first_name
        - name: last_name
      - name: raw_orders
        columns:
        - name: id
          tests:
            - not_null
            - unique
        - name: user_id
          tests:
            - relationships:
                to: source('etl', 'raw_customers')
                field: id
        - name: order_date
        - name: status
          tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'returned', 'return_pending']
      
      - name: raw_payments
        columns:
        - name: id
          tests:
            - not_null
            - unique
        - name: order_id
          tests:
            - relationships:
                to: source('etl', 'raw_orders')
                field: id
        - name: payment_method
          tests:
            - accepted_values:
                values: ['credit_card', 'bank_transfer', 'coupon', 'gift_card']
        - name: amount